# Generated by Django 4.0.4 on 2022-06-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_service', '0006_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
    ]
