# Generated by Django 4.0.4 on 2022-06-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_service', '0008_order_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logistician',
            name='user',
        ),
        migrations.AddField(
            model_name='logistician',
            name='login',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistician',
            name='password',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
